<?php
/**
 * Created by PhpStorm.
 * User: tomek
 * Date: 11.11.17
 * Time: 16:17
 */
include_once "lib/Baza.php";

class UserDB extends User
{
    /**
     * @var Baza
     */
    private static $db;

    /**
     * UserDB constructor.
     */
    public function __construct($user_name, $full_name, $email, $password)
    {
        parent::__construct($user_name, $full_name, $email, $password);
        self::linkDatabaseIfNotPresent();

    }

    private static function linkDatabaseIfNotPresent(){
        if(!isset($db)) self::$db = new Baza("localhost", "root", "tom123", "klienci");
    }

    /**
     * @return Baza
     */
    public static function getDb(): Baza
    {
        self::linkDatabaseIfNotPresent();
        return self::$db;
    }

    /**
     * @return bool
     */
    public function save() : bool
    {
        //parent::save(); // TODO: Change the autogenerated stub

        $sql = ("INSERT INTO klienci.users(user_name,full_name,email,passwd,status,created_at,logged_at) VALUES ");

        $valuesArr = array();
        $_user_name = self::$db->prepareData($this->user_name);
        $_full_name = self::$db->prepareData($this->full_name);
        $_email = self::$db->prepareData($this->email);
        $_passwd = self::$db->prepareData($this->passwd);
        $_status = self::$db->prepareData($this->status);
        $_created_at =  $this->date->format("Y-m-d H:i:s");
        $_logged_at = new DateTime();
        $_logged_at = $_logged_at->format("Y-m-d H:i:s");

        $valuesArr[] = "('$_user_name', '$_full_name', '$_email', '$_passwd', '$_status','$_created_at','$_logged_at')";

        $sql .= implode(',', $valuesArr);
        echo $sql;

        return self::$db->insert($sql);

    }

    /**
     *
     */
    public static function getAllUsers()
    {
        self::linkDatabaseIfNotPresent();
        echo self::$db->select("select full_name, logged_at from klienci.users", array("full_name","logged_at"));

    }






}